### PR TITLE
UseStaticFiles is supposed to come before UseRouting

### PR DESCRIPTION
**Pull request by VictorioBerra**
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-startupconfigure

### CODE REVIEW

**Comment by RehanSaeed** [comment]
If you want static files to also support CORS, then they have to appear after `UseRouting`. I'm not sure why someone would want CORS for static files, I was thinking someone could add a JSON static file and CORS would be useful for that.

What are your thoughts?

**Comment by VictorioBerra** [comment]
Yeah I wasn't aware the browser would make a preflight request for static
resources... If that's the case then we should leave it how you had it. Odd
but I suppose it makes sense. Did you do a quick test and verify it worked?
I'm not at a computer right now

**Comment by RehanSaeed** [comment]
The CORS docs said to do it this way. I'm actually going to merge your change though, I'm not sure CORS for static files is required.

**Comment by RehanSaeed** [comment]
Swashbuckle has the ability to use precompiled JSON for the open api definition. Been meaning to use that instead of the current runtime generated JSON. I'll leave it as is for now.

I will take your change to fix the Swagger server setting though.

**Comment by VictorioBerra** [comment]
Can you send me the docs on the precompiled json?

**Comment by RehanSaeed** [comment]
Not tried it yet, going to do some testing after upgrading Swashbuckle code properly.

I can't seem to find it in their docs anymore. I think it was a preview/beta last time I checked. I'll see if I can dig it out.

**Comment by RehanSaeed** [comment]
The `Swashbuckle.AspNetCore.Cli` package provides this functionality.

**Comment by VictorioBerra** [comment]
So what's the goal here? Generate it at build time and then serve it? Just performance? What if you need dynamically built swagger doc like when you change the host based on the request for hosting behind load balancers etc.

**Comment by RehanSaeed** [comment]
Performance mainly. In that scenario, you'd stick to using runtime generation. I'm considering adding it by default. Thoughts?

**Comment by VictorioBerra** [comment]
I think I would keep it the way it is honestly. I don't think performance
is much of a concern around swagger since it's mainly documentation or it's
used for client generation. Keeping it runtime generated means you don't
have to manage another asset in your project and have additional build time
steps and also it's more extensible as we are seeing with this host header
thing.

**Comment by VictorioBerra** [comment]
@RehanSaeed Why not move ApiVersionOperationFilter and CorrelationIdOpFilt to Boxed.Framework?

**Comment by RehanSaeed** [comment]
Yes, I'll consider that. The API template is almost done. All tests pass. Remaining:

- Need to fix all schema filters. I think you can now add comments like `<example>foo</example>` instead of using schema filters.
- I was going to look into https://github.com/Dotnet-Boxed/Framework/issues/27.
- Going to watch and read some stuff about Open API 3.

**Comment by VictorioBerra** [comment]
> Need to fix all schema filters. I think you can now add comments like <example>foo</example> instead of using schema filters.

That sounds interesting, got a link to any docs? Id like to look at it

**Comment by RehanSaeed** [comment]
Check the latest commit. The docs are on the swashbuckle home page.

**Pull request closed without merging**
