### PR TITLE
Add build using NUKE

### PR DESCRIPTION
**Pull request by matkoch**
Related to https://github.com/Dotnet-Boxed/Templates/issues/360

### CODE REVIEW

**Comment by VictorioBerra** [comment]
Thanks for this example! I am a heavy CAKE user but new to NUKE.

I like that NUKE seems to be a regular .csproj file, and the build.ps1/sh files look far simpler thank CAKES. It means I can use a normal IDE instead of having to use something like VSCode + CAKE extension and debug simply by executing the whole script.

But I am not sure I like having to maintain a .csproj full of Nuke specific stuff (IE `NukeSpecificationFiles` and `NukeExternalFiles`). I had to look up why all that was needed, it is not super discoverable. With CAKE everything you could possibly need to know lives in the CAKE file.

Id be interested in hearing your thoughts. How does Bulseye and SimpleExec compare to NUKE?

**Comment by matkoch** [comment]
I'm not sure what you mean by maintaining. The existing definitions for `NukeSpecificationFiles` and `NukeExternalFiles` are for convenience, so that whenever you're using those two features, you just need to add the required files. Other than that, you can just ignore them. I don't think that managing everything in a single file is a good idea. For instance, look at the difference in how external tools are defined.

I'm not really in the position to compare, but my guess is that nuke tries to be more of a framework, giving the maximum of integration with all build related technologies (tools, IDEs, CI server).

**Comment by VictorioBerra** [comment]
Yes, I am not a fan of getting external tools by using the CAKE includes at the top.

Having the NUKE libraries and such included as regular dotnet project package references is much cleaner and extensible. For example you can go as far as have dependabot alert you when there are updates to your NUKE tools/libs.

**Comment by matkoch** [comment]
That was the idea to integrate native tooling, not having to write everything from scratch.

**Comment by matkoch** [comment]
Are you interested in following up with this PR?

**Comment by VictorioBerra** [comment]
That is up to @RehanSaeed. I am fine either way.

CAKE is working fine as is today but NUKE has plenty of pros.

**Comment by RehanSaeed** [comment]
Thanks @matkoch for the effort. It's nice to be able to make a direct comparison between the two.

Since the original issue was raised, Cake released a new `dotnet cake` global tool instead of `build.sh` and `build.ps1` bootstrapper scripts which is what we've switched to using. This has made it a bit easier to use than it was in the past (where I would have called it out as Cake's most annoying problem). It also runs the script with .NET Core while the original bootstrapper scripts used .NET Framework, so that was also great since we no longer rely on Mono on linux build machines.

I'm surprised how similar the scripts look to each other. NUKE, seems to also have a library of helper methods which is great.

Not sure what the DotSettings file is about. It's also interesting that you include a bunch of CI server yml/json files, I'm not sure why that's needed.

Having a simple C# file is the killer feature I think. Upgrading NUKE as a NuGet package is also nice.

Overall, I'm happy with Cake, so don't see a reason to move to a tool that is unfamiliar and achieves the same goals albeit with the above small improvements.

**Comment by matkoch** [comment]
Hi @RehanSaeed 

You weren’t really asking, but I’ll give my two cents anyways.

> I'm surprised how similar the scripts look to each other. NUKE, seems to also have a library of helper methods which is great.

The biggest difference is full IDE support. Refactorings, navigation, and debugging – no matter which IDE you’re using. Another one is that bootstrapping for CI systems is generated and uses parallelization out of the box (for example https://github.com/nuke-build/nuke/blob/develop/azure-pipelines.yml).

> Not sure what the DotSettings file is about.

Dotsettings and editorconfig is for proper formatting. Again, a feature only available in nuke.

> It's also interesting that you include a bunch of CI server yml/json files, I'm not sure why that's needed.

The CI configuration files are (conditionally) included for convenience. You’d see them when opening the build project, which I think makes sense. Thanks for the point though, I think this part can be moved to the NuGet targets file to clean up the csproj file.

> Having a simple C# file is the killer feature I think. Upgrading NUKE as a NuGet package is also nice.

Thanks. Apparently not killer enough ;)

**Comment by RehanSaeed** [comment]
It's killer enough for me to try it on something small and new. I'll revisit this PR when I get a feel for using it. Thank you for your input, really appreciated.

**Pull request closed without merging**
