### PR TITLE
Set Latest Analysis Level

### PR DESCRIPTION
**Pull request by RehanSaeed**

### CODE REVIEW

**Comment by VictorioBerra** [comment]
Why is this needed?

**Comment by RehanSaeed** [comment]
I suppose it's like `<LangVersion>latest</LangVersion>`. The blog post suggests that you can use version 5 with .NET Core 3.1, although I'm not certain on that. Also, in the future there may be reason to add `latest` if you are running on an older SDK.

**Comment by VictorioBerra** [comment]
Can you link me to the blog? I may have missed it. I need to update my bookmarks.

**Comment by RehanSaeed** [comment]
https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/

**Pull request merged**
