### PR TITLE
Upgrade to .NET SDK 5.0.100

### PR DESCRIPTION
**Pull request by RehanSaeed**
Fixes https://github.com/Dotnet-Boxed/Templates/issues/762 and https://github.com/Dotnet-Boxed/Templates/issues/864

- Upgrade to .NET Core SDK 5.0.100.
- Use latestMajor .NET SDK.
- Bump Cake.Tool from 0.38.5 to 1.0.0.
- Update the `.editorconfig` file which has changed in a breaking way (https://github.com/RehanSaeed/EditorConfig/pull/42) to support VS 16.8.
- Enable `EnforceCodeStyleInBuild` (This is awesome) if `EditorConfig` is enabled.
- Switch from `is object` to `is not null`. This has been on my mind for a long time. There is a lot more that could be done but getting some C# 9 in early.
- No longer need to set `Activity.DefaultIdFormat`, so remove it.
- Update Docker base images`
- Add `**/launchSettings.json` to `.dockerignore`.
- Disable reloading configuration on change.
- Enable `dotnetRunMessages` for dotnet run based launch settings in `launchSettings.json`.
- Enable HealthCheck in Orleans template authoring mode.
- Configure Kestrel from "Kestrel" configuration section.
- Add `Serilog.Enrichers.Span` to log details from `System.Diagnostics.Activity`.
- Fixed https://github.com/Dotnet-Boxed/Templates/issues/867 by doubling `MaxRequestHeaderCount` to 40.
- Switch from using `<NoWarn>` csproj property to `.editorconfig` to supress rules.
- Orleans `ClusterFixture` now uses new `async`/`await` API's in Orleans to setup and tear down a cluster in a test.
- Log application name and environment on application start, stop and exception.
- Remove `TestStartup` class from API and GraphQL templates.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
@VictorioBerra Removed logging to the event log. It turns out you need to run VS with admin priveledges at least once to be able to create an event source. Otherwise you just get security exceptions. That was a terrible experience, plus it was Windows only, so I removed it.

**Comment by VictorioBerra** [comment]
Sounds good, users can add it manually if they really want it. And its not like anyone created an issue asking for it here. So I think its safe to omit. I wonder why Microsoft made it default in the new templates?

**Comment by RehanSaeed** [comment]
They must have a way to get around creating the event log source.

**Comment by RehanSaeed** [comment]
@VictorioBerra Only outstanding issues remaining are figuring out the issue around integration tests (Say you add to that thread) and understanding `dotnetRunMessages` better so I can add it in more places potentially.

The integration tests currently work after I added a workaround but I don't really understand why.

**Comment by VictorioBerra** [comment]
@RehanSaeed Honestly I did not like the TestStartup class for the same reason I dont like having appsettings.tests and I think removing it is the smart play and makes the test stuff more discoverable anyway by keeping it in one place and leveraging the existing features of the WAF. I like the changes so far!

**Comment by RehanSaeed** [comment]
Not sure we can do anything about `appsettings.Test.json`. We need it to override the default production host. Made the changes to remove `TestStartup`. In that case going to complete the PR.

**Pull request merged**
