### PR TITLE
Remove Git option to add something better

### PR DESCRIPTION
**Pull request by RehanSaeed**

### CODE REVIEW

**Comment by VictorioBerra** [comment]
When I initialize a new repository I use https://www.toptal.com/developers/gitignore I actually use a CLI wrapper included here https://github.com/tj/git-extras

https://github.com/tj/git-extras/blob/master/Commands.md#git-ignore-io

**Comment by RehanSaeed** [comment]
The .gitignore I include is the VisualStudio one which is also available from the site you mention.

**Comment by VictorioBerra** [comment]
Have you added it yet? I might be missing it here on the GitHub files tab. Or does VS add it when the solution is opened?

**Comment by RehanSaeed** [comment]
It's in there already. There was a bug a few weeks back where files starting with a `.` were not being included in the template but I fixed that.

**Comment by RehanSaeed** [comment]
See https://github.com/Dotnet-Boxed/Templates/pull/731 for the new options being added.

**Pull request merged**
